# Generated by Django 3.2.7 on 2021-12-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211223_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='driver_name',
            new_name='driver',
        ),
    ]
